project:
  type: default
  render:
    - santagostini_multvardiv.qmd
    - README.qmd

title: "`multvardiv` package"
subtitle: "Multivariate elliptical Distributions and Statistical Divergence"
author:
  - name: Pierre Santagostini
    corresponding: true
    email: pierre.santagostini@institut-agro.fr
    affiliations:
      - name: Univ Angers, Institut Agro, INRAE, IRHS, SFR QUASAV, F-49000 Angers, France
        department: ImHorPhen (Imaging for Horticulture and Phenotyping) team
        url: https://www6.angers-nantes.inrae.fr/irhs
  - name: Nizar Bouhlel
    email: nizar.bouhlel@institut-agro.fr; nizar.bouhlel@inrae.fr
    url: https://www.researchgate.net/profile/Nizar-Bouhlel
    orcid: 0000-0002-4861-8550
    affiliations:
      - name: Univ Angers, Institut Agro, INRAE, IRHS, SFR QUASAV, F-49000 Angers, France
        department: ImHorPhen (Imaging for Horticulture and Phenotyping) team
        url: https://www6.angers-nantes.inrae.fr/irhs
date: last-modified
date-modified: last-modified
description: |
  The R package `multvardiv` provides functions to compute the Kullback-Leibler divergence between two multivariate $t$, Cauchy or generalized Gaussian distributions using analytic expressions of the divergence. For the $t$ and Cauchy distributions, the Rényi, Bhattacharyya and Hellinger divergences are also available. This package also gives tools for the manipulation of these distributions: probability density function, simulation of a random sample, estimation of the parameters, graph.
abstract: >+
  The R package `multvardiv` provides functions to compute the Kullback-Leibler divergence between two multivariate $t$, Cauchy or generalized Gaussian distributions using analytic expressions of the divergence. For the $t$ and Cauchy distributions, the Rényi, Bhattacharyya and Hellinger divergences are also available. This package also gives tools for the manipulation of these distributions: probability density function, simulation of a random sample, estimation of the parameters, graph.
keywords: [multivariate generalized Gaussian distribution, multivariate t distribution, multivariate Cauchy distribution, Kullback-Leibler divergence]
bibliography: references.bib
github-user: computorg
repo: "template-computo-r"
draft: true # set to false once the build is running
published: false # will be set to true once accepted
license: CC-BY-4.0
format:
  computo-html: default
  computo-pdf: default